# TryCatchWrapper
用try catch包裹你的函数，避免报错
